blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment , name='post_comment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return (super().get_queryset().filter(status=Post.Status.PUBLISHED))

class Post (models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PB', 'Published'

    objects = models.Manager()
    published = PublishedManager()

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status,
                              default=Status.DRAFT)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name="blog_posts")

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
            ]

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments'
    )
    name = models.CharField(max_length=30)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )


from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.decorators.http import require_POST
from .forms import CommentForm, EmailPostForm
from django.views.generic import ListView

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

# EQUIVALENT

def post_list(request):
    posts_list = Post.published.all()

    paginator = Paginator(posts_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    #we could use except : with no exception
    
    return render(request, 'blog/post/list.html', {'posts' : posts})

def post_detail(request, year, month, day, post):
    post =  get_object_or_404(Post,
                              publish__year=year,
                              publish__month=month,
                              publish__day=day,
                              slug=post,
                              status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return (render(request,
                   'blog/post/detail.html',
                   {'post':post, 'comments':comments, 'form':form}))

# from django.core.mail import send_mail

def post_share(request, post_id):
    sent = False
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    if (request.method == 'POST'):
        form = EmailPostForm(request.POST)
        if (form.is_valid()):
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']})"
                f"recommends you read {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']} comments: {cd['comments']}"
            )
            sent = True
    else:
        form = EmailPostForm()
    return (render(request,
                   'blog/post/share.html',
                   {'post': post,'form':form, 'sent': sent}))



@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if (form.is_valid()):
        comment = form.save(commit=False) #to not save it to database directly, cause we will modify here on the post before submitting here
        comment.post = post
        comment.save() #saved to the db
    return (render(request,
                   'blog/post/comment.html',
                   {'post':post, 'form':form, 'comment':comment}))

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %} {% endblock %}
        </title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>My blog</h2>
            <p>this is my blog</p>
        </div>
    </body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}ADD a comment{%endblock%}

{%block content%}
    {%if comment %}
        <h2>your comment has been added</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {%else%}
        {% include "blog/post/includes/comment_form.html" %}
    {%endif%}
{%endblock%}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{post.title}} {%endblock%}

{%block content%}
    <h1>{{posta.title}}</h1>
    <p class="date"> Published {{post.publish}} by {{post.author}} </p>
    {{post.body | linebreaks}}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share This post
        </a>
    </p>
    {% with comments.count as comment_max%}
        <h2>
            {{comment_max}} comment{{ comment_max|pluralize }}
        </h2>
    {% endwith %}

    {% for com in comments%}
        <div class="comment">
            <p class="info">
                Comment {{forloop.counter}} by {{com.name}}
                {{com.created}}
            </p>
            {{com.body|linebreaks}}
        </div>
    {% empty %}
        <p>No comments.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html"%}
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2> add comment here </h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    <div class="left">
        {{ form.name.as_field_group}}
    </div>
    <div class="left">
        {{ form.email.as_field_group}}
    </div>
    {{form.body.as_field_group}}
    {% csrf_token %}
    <p><input type="submit" value="add comment"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title%}My blog{% endblock %}

{% block content %}
    <h1>My blog</h1>
    {% for post in posts%}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body | truncatewords:30 | linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{%block title%}Share a post{%endblock%}

{%block content%}
    {%if sent%}
        <h1>Email sent successfuly</h1>
    {% else %}
        <h1> share "{{ post.title }}" by email </h1>
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="send mail">
        </form>
    {% endif %}
{%endblock%}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {%if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">
                Previous 
            </a>
        {%endif%}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">
                Next
            </a>
        {% endif %}
    </span>
</div>